title: Akash Chatterjee
description: Personal website and blog of Akash Chatterjee.

navigation:
  - title: Home
    url: /
  - title: Tech
    url: /tech/
  - title: Travel
    url: /travel/
  - title: Opinions
    url: /opinions/