title: Akash Chatterjee
description: Personal website and blog of Akash Chatterjee.

navigation:
  - title: home
    url: /
  - title: tech
    url: /tech/
  - title: travel
    url: /travel/
  - title: opinions
    url: /opinions/