title: Akash Chatterjee
description: Personal website and blog of Akash Chatterjee.
url: "https://akashchatterjee.com"
baseurl: ""

# Author information
author:
  name: Akash Chatterjee
  image: /assets/images/profile.jpg

# SEO Settings
lang: en_US
logo: /assets/images/profile.jpg
image: /assets/images/profile.jpg

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Jekyll settings
permalink: /:categories/:year/:month/:day/:title/
timezone: America/New_York

navigation:
  - title: Home
    url: /
  - title: Tech
    url: /tech/
  - title: Travel
    url: /travel/
  - title: Opinions
    url: /opinions/